#include "stdint.h"

#ifndef KEYBOARD_H
#define KEYBOARD_H

extern void kbd_init(void);
extern void kbd_isr(void);
extern char getc();

// My Keycodes

#define KEY_ESC_PRESSED         0x10
#define KEY_ESC_RELEASED        0x11
#define KEY_F1_PRESSED          0x12
#define KEY_F1_RELEASED         0x13
#define KEY_F2_PRESSED          0x14
#define KEY_F2_RELEASED         0x15
#define KEY_F3_PRESSED          0x16
#define KEY_F3_RELEASED         0x17
#define KEY_F4_PRESSED          0x18
#define KEY_F4_RELEASED         0x19
#define KEY_F5_PRESSED          0x1a
#define KEY_F5_RELEASED         0x1b
#define KEY_F6_PRESSED          0x1c
#define KEY_F6_RELEASED         0x1d
#define KEY_F7_PRESSED          0x1e
#define KEY_F7_RELEASED         0x1f
#define KEY_F8_PRESSED          0x20
#define KEY_F8_RELEASED         0x21
#define KEY_F9_PRESSED          0x22
#define KEY_F9_RELEASED         0x23
#define KEY_F10_PRESSED         0x24
#define KEY_F10_RELEASED        0x25
#define KEY_F11_PRESSED         0x26
#define KEY_F11_RELEASED        0x27
#define KEY_F12_PRESSED         0x28
#define KEY_F12_RELEASED        0x29
#define KEY_PRINT_PRESSED       0x2a
#define KEY_PRINT_RELEASED      0x2b
#define KEY_SCRLK_PRESSED       0x2c
#define KEY_SCRLK_RELEASED      0x2d
#define KEY_PAUSE_PRESSED       0x2e
#define KEY_PAUSE_RELEASED      0x2f

#define KEY_BACKTICK_PRESSED    0x30
#define KEY_BACKTICK_RELEASED   0x31
#define KEY_1_PRESSED           0x32
#define KEY_1_RELEASED          0x33
#define KEY_2_PRESSED           0x34
#define KEY_2_RELEASED          0x35
#define KEY_3_PRESSED           0x36
#define KEY_3_RELEASED          0x37
#define KEY_4_PRESSED           0x38
#define KEY_4_RELEASED          0x39
#define KEY_5_PRESSED           0x3a
#define KEY_5_RELEASED          0x3b
#define KEY_6_PRESSED           0x3c
#define KEY_6_RELEASED          0x3d
#define KEY_7_PRESSED           0x3e
#define KEY_7_RELEASED          0x3f
#define KEY_8_PRESSED           0x40
#define KEY_8_RELEASED          0x41
#define KEY_9_PRESSED           0x42
#define KEY_9_RELEASED          0x43
#define KEY_0_PRESSED           0x44
#define KEY_0_RELEASED          0x45
#define KEY_MINUS_PRESSED       0x46
#define KEY_MINUS_RELEASED      0x47
#define KEY_EQUAL_PRESSED       0x48
#define KEY_EQUAL_RELEASED      0x49
#define KEY_BACKSPACE_PRESSED   0x4a
#define KEY_BACKSPACE_RELEASED  0x4b
#define KEY_INSERT_PRESSED      0x4c
#define KEY_INSERT_RELEASED     0x4d
#define KEY_HOME_PRESSED        0x4e
#define KEY_HOME_RELEASED       0x4f
#define KEY_PGUP_PRESSED        0x50
#define KEY_PGUP_RELEASED       0x51

#define KEY_TAB_PRESSED         0x52
#define KEY_TAB_RELEASED        0x53
#define KEY_Q_PRESSED           0x54
#define KEY_Q_RELEASED          0x55
#define KEY_W_PRESSED           0x56
#define KEY_W_RELEASED          0x57
#define KEY_E_PRESSED           0x58
#define KEY_E_RELEASED          0x59
#define KEY_R_PRESSED           0x5a
#define KEY_R_RELEASED          0x5b
#define KEY_T_PRESSED           0x5c
#define KEY_T_RELEASED          0x5d
#define KEY_Y_PRESSED           0x5e
#define KEY_Y_RELEASED          0x5f
#define KEY_U_PRESSED           0x60
#define KEY_U_RELEASED          0x61
#define KEY_I_PRESSED           0x62
#define KEY_I_RELEASED          0x63
#define KEY_O_PRESSED           0x64
#define KEY_O_RELEASED          0x65
#define KEY_P_PRESSED           0x66
#define KEY_P_RELEASED          0x67
#define KEY_BRACKETOP_PRESSED   0x68
#define KEY_BRACKETOP_RELEASED  0x69
#define KEY_BRACKETCL_PRESSED   0x6a
#define KEY_BRACKETCL_RELEASED  0x6b
#define KEY_BACKSLASH_PRESSED   0x6c
#define KEY_BACKSLASH_RELEASED  0x6d
#define KEY_DELETE_PRESSED      0x6e
#define KEY_DELETE_RELEASED     0x6f
#define KEY_END_PRESSED         0x70
#define KEY_END_RELEASED        0x71
#define KEY_PGDOWN_PRESSED      0x72
#define KEY_PGDOWN_RELEASED     0x73

#define KEY_CAPS_PRESSED        0x74
#define KEY_CAPS_RELEASED       0x75
#define KEY_A_PRESSED           0x76
#define KEY_A_RELEASED          0x77
#define KEY_S_PRESSED           0x78
#define KEY_S_RELEASED          0x79
#define KEY_D_PRESSED           0x7a
#define KEY_D_RELEASED          0x7b
#define KEY_F_PRESSED           0x7c
#define KEY_F_RELEASED          0x7d
#define KEY_G_PRESSED           0x7e
#define KEY_G_RELEASED          0x7f
#define KEY_H_PRESSED           0x80
#define KEY_H_RELEASED          0x81
#define KEY_J_PRESSED           0x82
#define KEY_J_RELEASED          0x83
#define KEY_K_PRESSED           0x84
#define KEY_K_RELEASED          0x85
#define KEY_L_PRESSED           0x86
#define KEY_L_RELEASED          0x87
#define KEY_SEMICOLON_PRESSED   0x88
#define KEY_SEMICOLON_RELEASED  0x89
#define KEY_QUOTE_PRESSED       0x8a
#define KEY_QUOTE_RELEASED      0x8b
#define KEY_RETURN_PRESSED      0x8c
#define KEY_RETURN_RELEASED     0x8d

#define KEY_SHIFTL_PRESSED      0x8e
#define KEY_SHIFTL_RELEASED     0x8f
#define KEY_Z_PRESSED           0x90
#define KEY_Z_RELEASED          0x91
#define KEY_X_PRESSED           0x92
#define KEY_X_RELEASED          0x93
#define KEY_C_PRESSED           0x94
#define KEY_C_RELEASED          0x95
#define KEY_V_PRESSED           0x96
#define KEY_V_RELEASED          0x97
#define KEY_B_PRESSED           0x98
#define KEY_B_RELEASED          0x99
#define KEY_N_PRESSED           0x9a
#define KEY_N_RELEASED          0x9b
#define KEY_M_PRESSED           0x9c
#define KEY_M_RELEASED          0x9d
#define KEY_COMMA_PRESSED       0x9e
#define KEY_COMMA_RELEASED      0x9f
#define KEY_DOT_PRESSED         0xa0
#define KEY_DOT_RELEASED        0xa1
#define KEY_SLASH_PRESSED       0xa2
#define KEY_SLASH_RELEASED      0xa3
#define KEY_SHIFTR_PRESSED      0xa4
#define KEY_SHIFTR_RELEASED     0xa5
#define KEY_UP_PRESSED          0xa6
#define KEY_UP_RELEASED         0xa7

#define KEY_CTRLL_PRESSED       0xa8
#define KEY_CTRLL_RELEASED      0xa9
#define KEY_SUPERL_PRESSED      0xaa
#define KEY_SUPERL_RELEASED     0xab
#define KEY_ALT_PRESSED        0xac
#define KEY_ALT_RELEASED       0xad
#define KEY_SPACE_PRESSED       0xae
#define KEY_SPACE_RELEASED      0xaf
#define KEY_ALTGR_PRESSED        0xb0
#define KEY_ALTGR_RELEASED       0xb1
#define KEY_SUPERR_PRESSED      0xb2
#define KEY_SUPERR_RELEASED     0xb3
#define KEY_MENU_PRESSED        0xb4
#define KEY_MENU_RELEASED       0xb5
#define KEY_CTRLR_PRESSED       0xb6
#define KEY_CTRLR_RELEASED      0xb7
#define KEY_LEFT_PRESSED        0xb8
#define KEY_LEFT_RELEASED       0xb9
#define KEY_DOWN_PRESSED        0xba
#define KEY_DOWN_RELEASED       0xbb
#define KEY_RIGHT_PRESSED       0xbc
#define KEY_RIGHT_RELEASED      0xbd

#define KEY_NUM_NUMLK_PRESSED   0xbe
#define KEY_NUM_NUMLK_RELEASED  0xbf
#define KEY_NUM_DIV_PRESSED     0xc0
#define KEY_NUM_DIV_RELEASED    0xc1
#define KEY_NUM_MULT_PRESSED    0xc2
#define KEY_NUM_MULT_RELEASED   0xc3
#define KEY_NUM_SUB_PRESSED     0xc4
#define KEY_NUM_SUB_RELEASED    0xc5

#define KEY_NUM_7_PRESSED       0xc6
#define KEY_NUM_7_RELEASED      0xc7
#define KEY_NUM_8_PRESSED       0xc8
#define KEY_NUM_8_RELEASED      0xc9
#define KEY_NUM_9_PRESSED       0xca
#define KEY_NUM_9_RELEASED      0xcb
#define KEY_NUM_ADD_PRESSED     0xcc
#define KEY_NUM_ADD_RELEASED    0xcd

#define KEY_NUM_4_PRESSED       0xce
#define KEY_NUM_4_RELEASED      0xcf
#define KEY_NUM_5_PRESSED       0xd0
#define KEY_NUM_5_RELEASED      0xd1
#define KEY_NUM_6_PRESSED       0xd2
#define KEY_NUM_6_RELEASED      0xd3

#define KEY_NUM_1_PRESSED       0xd4
#define KEY_NUM_1_RELEASED      0xd5
#define KEY_NUM_2_PRESSED       0xd6
#define KEY_NUM_2_RELEASED      0xd7
#define KEY_NUM_3_PRESSED       0xd8
#define KEY_NUM_3_RELEASED      0xd9
#define KEY_NUM_ENTER_PRESSED   0xda
#define KEY_NUM_ENTER_RELEASED  0xdb

#define KEY_NUM_0_PRESSED       0xdc
#define KEY_NUM_0_RELEASED      0xdd
#define KEY_NUM_DOT_PRESSED     0xde
#define KEY_NUM_DOT_RELEASED    0xdf


#endif

